# fly.toml app configuration file generated for deepgram-youtube-demo on 2023-06-13T17:18:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deepgram-youtube-demo"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1